# Generated by Django 2.0.4 on 2018-04-08 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('readstatistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read_num', models.IntegerField(default=0, verbose_name='今天阅读量')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 4, 8, 6, 30, 29, 878050, tzinfo=utc))),
                ('object_id', models.PositiveIntegerField(verbose_name='对象id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '每天阅读详情',
                'verbose_name_plural': '每天阅读详情',
            },
        ),
    ]
