# Generated by Django 2.0.4 on 2018-04-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pub_status',
            field=models.BooleanField(default=True, verbose_name='发布状态'),
        ),
    ]
