# Generated by Django 2.0.4 on 2018-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_pub_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_cate', models.CharField(max_length=32, verbose_name='一级分类')),
                ('second_cate', models.CharField(max_length=32, verbose_name='二级分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
    ]
