# Generated by Django 2.0.4 on 2018-04-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180407_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除?'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pub_status',
            field=models.BooleanField(default=True, verbose_name='发布?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, verbose_name='分类'),
        ),
    ]
