# Generated by Django 2.0.4 on 2018-04-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象id')),
                ('cmt_detail', models.TextField(verbose_name='评论内容')),
                ('cmt_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('cmt_is_delete', models.BooleanField(default=False, verbose_name='已删除?')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='评论对象')),
            ],
        ),
    ]
