# Generated by Django 2.0.4 on 2018-04-13 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_auto_20180410_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rpy_parent', to='comment.Comments', verbose_name='评论父节点'),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rpy_root', to='comment.Comments', verbose_name='评论起点'),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rpy_user', to=settings.AUTH_USER_MODEL, verbose_name='回复用户'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='cmt_is_delete',
            field=models.BooleanField(default=False, verbose_name='删除?'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='cmt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmt_user', to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
    ]
