# Generated by Django 2.0.4 on 2018-04-19 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20180414_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cmt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt_user', to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='评论对象'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reply_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpy_parent', to='comment.Comments', verbose_name='评论父节点'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reply_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpy_root', to='comment.Comments', verbose_name='评论根节点'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reply_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpy_user', to=settings.AUTH_USER_MODEL, verbose_name='回复用户'),
        ),
    ]
